### ISSUE TITLE
No subtitles found,debug included ,Limit access free plan

### ISSUE THREAD

**Issue by Program-Evolved** [justchokingaround/lobster#201] opened 2024-04-23 21:00 UTC
**Describe the bug**
can't watch anything the only output is "no subtitle found"
retried with debug on and got this [output](https://pastebin.com/JJBXicRk)

**To Reproduce**
1-install latest version
2-try to watch something
3-no subtitles found

**Expected behavior**
movie starts.

**Desktop (please complete the following information):**
 - OS: windows 10/wsl 2 debian
 - Browser: firefix
 - Version : 125.0.1

**Additional context**
"+ printf %s {"data":null,"message":"Too Many Requests, reason: Limit access free plan","warning":"Unlimited and high performance for just $160/month, Contact us Email: hqapiapp@gmail.com, Discord: freeapi","purchase_now":"https://fffapifree.cam"}"

**Comment by dinesh-58** [comment] 2024-04-29 10:14
duplicate of #193 

from https://github.com/justchokingaround/lobster/issues/199#issuecomment-2046007289:
> yeah we'll fix it soon. i just have exams atm and ciaran is a bit busy with other things

**Comment by justchokingaround** [comment] 2024-04-30 21:49
im closing this as a duplicate, ty @dinesh-58

**Closed by justchokingaround** 2024-04-30 21:49 UTC
