### ISSUE TITLE
"No subtitles found"

### ISSUE THREAD

**Issue by aryan-212** [justchokingaround/lobster#198] opened 2024-04-08 07:34 UTC
Log Output :- 

```
+ debug=1
+ shift
+ '[' 0 -gt 0 ']'
++ printf %s ''
++ tr ' ' -
++ sed 's/^-//g'
+ query=
+ '[' 0 = 1 ']'
+ '[' -z Vidcloud ']'
+ '[' '' = 1 ']'
+ '[' '' = movie ']'
+ '[' '' = tv ']'
+ main
+ '[' -z '' ']'
+ '[' -z '' ']'
+ get_input
+ '[' 0 = 0 ']'
+ printf 'Search Movie/TV Show: '
Search Movie/TV Show: + read -r query
The Platform
+ '[' -n 'The Platform' ']'
++ echo 'The Platform'
++ tr ' ' -
+ query=The-Platform
+ '[' -z The-Platform ']'
+ search The-Platform
+ '[' 0 = 1 ']'
++ curl -s https://flixhq.to/search/The-Platform
++ sed ':a;N;$!ba;s/\n//g;s/class="flw-item"/\n/g'
++ sed -nE 's@.*<a href=".*/(tv|movie)/watch-.*-([0-9]*)".*title="([^"]*)".*class="fdi-item">([^<]*)</span>.*@\3 (\1) [\4]\t\2@p'
++ hxunent
+ response='The Platform (movie) [2019]	49941
The Weapon, the Hour, the Motive (movie) [1972]	87856
The Gangster, the Cop, the Devil (movie) [2019]	66106
The Chef, The Actor, The Scoundrel (movie) [2013]	57012
The Good, The Bad, The Weird (movie) [2008]	54680
The Simpsons: The Good, the Bart, and the Loki (movie) [2021]	70646
The Boy, the Mole, the Fox and the Horse (movie) [2022]	91783
The Mother the Son The Rat and The Gun (movie) [2021]	79075
The Power, The Passion (tv) [EPS ]	26458
The Darker the Lake (movie) [2022]	94237
The Knight & The Princess (movie) [2020]	65418
The Dish & the Spoon (movie) [2011]	57914
The Transformers: The Movie (movie) [1986]	53726
The Great & The Small (movie) [2016]	56316
The Hottie & The Nottie (movie) [2008]	4836
The Good, the Bad and the Ugly (movie) [1966]	19502
The Billionaire, The Butler, and the Boyfriend (tv) [EPS 3]	102523
The Author, The Star, and The Keeper (movie) [2020]	63843
The Prince and the Pauper: The Movie (movie) [2007]	64450
The Dead the Damned and the Darkness (movie) [2014]	56934
The Boy, the Dog and the Clown (movie) [2019]	58875
The Butcher, the Chef, and the Swordsman (movie) [2011]	53714
The Pig, the Snake and the Pigeon (movie) [2023]	106828
The Lord of the Rings: The Return of the King (movie) [2003]	19681
The Lord of the Rings: The Fellowship of the Ring (movie) [2001]	19736
The Woman in the House Across the Street from the Girl in the Window (tv) [EPS 8]	76804
The Chronicles of Narnia: The Lion, the Witch and the Wardrobe (movie) [2005]	19545
The Adventurer: The Curse of the Midas Box (movie) [2013]	9272
The Librarian: The Curse of the Judas Chalice (movie) [2008]	9628
The Lord of the Rings: The Two Towers (movie) [2002]	19670
The Hobbit: The Battle of the Five Armies (movie) [2014]	19785
The Island at the Top of the World (movie) [1974]	70190'
+ '[' -z 'The Platform (movie) [2019]	49941
The Weapon, the Hour, the Motive (movie) [1972]	87856
The Gangster, the Cop, the Devil (movie) [2019]	66106
The Chef, The Actor, The Scoundrel (movie) [2013]	57012
The Good, The Bad, The Weird (movie) [2008]	54680
The Simpsons: The Good, the Bart, and the Loki (movie) [2021]	70646
The Boy, the Mole, the Fox and the Horse (movie) [2022]	91783
The Mother the Son The Rat and The Gun (movie) [2021]	79075
The Power, The Passion (tv) [EPS ]	26458
The Darker the Lake (movie) [2022]	94237
The Knight & The Princess (movie) [2020]	65418
The Dish & the Spoon (movie) [2011]	57914
The Transformers: The Movie (movie) [1986]	53726
The Great & The Small (movie) [2016]	56316
The Hottie & The Nottie (movie) [2008]	4836
The Good, the Bad and the Ugly (movie) [1966]	19502
The Billionaire, The Butler, and the Boyfriend (tv) [EPS 3]	102523
The Author, The Star, and The Keeper (movie) [2020]	63843
The Prince and the Pauper: The Movie (movie) [2007]	64450
The Dead the Damned and the Darkness (movie) [2014]	56934
The Boy, the Dog and the Clown (movie) [2019]	58875
The Butcher, the Chef, and the Swordsman (movie) [2011]	53714
The Pig, the Snake and the Pigeon (movie) [2023]	106828
The Lord of the Rings: The Return of the King (movie) [2003]	19681
The Lord of the Rings: The Fellowship of the Ring (movie) [2001]	19736
The Woman in the House Across the Street from the Girl in the Window (tv) [EPS 8]	76804
The Chronicles of Narnia: The Lion, the Witch and the Wardrobe (movie) [2005]	19545
The Adventurer: The Curse of the Midas Box (movie) [2013]	9272
The Librarian: The Curse of the Judas Chalice (movie) [2008]	9628
The Lord of the Rings: The Two Towers (movie) [2002]	19670
The Hobbit: The Battle of the Five Armies (movie) [2014]	19785
The Island at the Top of the World (movie) [1974]	70190' ']'
+ '[' -z 'The Platform (movie) [2019]	49941
The Weapon, the Hour, the Motive (movie) [1972]	87856
The Gangster, the Cop, the Devil (movie) [2019]	66106
The Chef, The Actor, The Scoundrel (movie) [2013]	57012
The Good, The Bad, The Weird (movie) [2008]	54680
The Simpsons: The Good, the Bart, and the Loki (movie) [2021]	70646
The Boy, the Mole, the Fox and the Horse (movie) [2022]	91783
The Mother the Son The Rat and The Gun (movie) [2021]	79075
The Power, The Passion (tv) [EPS ]	26458
The Darker the Lake (movie) [2022]	94237
The Knight & The Princess (movie) [2020]	65418
The Dish & the Spoon (movie) [2011]	57914
The Transformers: The Movie (movie) [1986]	53726
The Great & The Small (movie) [2016]	56316
The Hottie & The Nottie (movie) [2008]	4836
The Good, the Bad and the Ugly (movie) [1966]	19502
The Billionaire, The Butler, and the Boyfriend (tv) [EPS 3]	102523
The Author, The Star, and The Keeper (movie) [2020]	63843
The Prince and the Pauper: The Movie (movie) [2007]	64450
The Dead the Damned and the Darkness (movie) [2014]	56934
The Boy, the Dog and the Clown (movie) [2019]	58875
The Butcher, the Chef, and the Swordsman (movie) [2011]	53714
The Pig, the Snake and the Pigeon (movie) [2023]	106828
The Lord of the Rings: The Return of the King (movie) [2003]	19681
The Lord of the Rings: The Fellowship of the Ring (movie) [2001]	19736
The Woman in the House Across the Street from the Girl in the Window (tv) [EPS 8]	76804
The Chronicles of Narnia: The Lion, the Witch and the Wardrobe (movie) [2005]	19545
The Adventurer: The Curse of the Midas Box (movie) [2013]	9272
The Librarian: The Curse of the Judas Chalice (movie) [2008]	9628
The Lord of the Rings: The Two Towers (movie) [2002]	19670
The Hobbit: The Battle of the Five Armies (movie) [2014]	19785
The Island at the Top of the World (movie) [1974]	70190' ']'
+ '[' 0 = 1 ']'
+ '[' 0 = 1 ']'
+ '[' 0 = 0 ']'
++ printf %s 'The Platform (movie) [2019]	49941
The Weapon, the Hour, the Motive (movie) [1972]	87856
The Gangster, the Cop, the Devil (movie) [2019]	66106
The Chef, The Actor, The Scoundrel (movie) [2013]	57012
The Good, The Bad, The Weird (movie) [2008]	54680
The Simpsons: The Good, the Bart, and the Loki (movie) [2021]	70646
The Boy, the Mole, the Fox and the Horse (movie) [2022]	91783
The Mother the Son The Rat and The Gun (movie) [2021]	79075
The Power, The Passion (tv) [EPS ]	26458
The Darker the Lake (movie) [2022]	94237
The Knight & The Princess (movie) [2020]	65418
The Dish & the Spoon (movie) [2011]	57914
The Transformers: The Movie (movie) [1986]	53726
The Great & The Small (movie) [2016]	56316
The Hottie & The Nottie (movie) [2008]	4836
The Good, the Bad and the Ugly (movie) [1966]	19502
The Billionaire, The Butler, and the Boyfriend (tv) [EPS 3]	102523
The Author, The Star, and The Keeper (movie) [2020]	63843
The Prince and the Pauper: The Movie (movie) [2007]	64450
The Dead the Damned and the Darkness (movie) [2014]	56934
The Boy, the Dog and the Clown (movie) [2019]	58875
The Butcher, the Chef, and the Swordsman (movie) [2011]	53714
The Pig, the Snake and the Pigeon (movie) [2023]	106828
The Lord of the Rings: The Return of the King (movie) [2003]	19681
The Lord of the Rings: The Fellowship of the Ring (movie) [2001]	19736
The Woman in the House Across the Street from the Girl in the Window (tv) [EPS 8]	76804
The Chronicles of Narnia: The Lion, the Witch and the Wardrobe (movie) [2005]	19545
The Adventurer: The Curse of the Midas Box (movie) [2013]	9272
The Librarian: The Curse of the Judas Chalice (movie) [2008]	9628
The Lord of the Rings: The Two Towers (movie) [2002]	19670
The Hobbit: The Battle of the Five Armies (movie) [2014]	19785
The Island at the Top of the World (movie) [1974]	70190'
++ fzf --reverse --with-nth 1 -d '\t' --header 'Choose a Movie or TV Show'
+ choice='The Platform (movie) [2019]	49941'
++ printf %s 'The Platform (movie) [2019]	49941'
++ sed -nE 's@(.*) \((movie|tv)\).*@\1@p'
+ title='The Platform'
++ printf %s 'The Platform (movie) [2019]	49941'
++ sed -nE 's@(.*) \((movie|tv)\).*@\2@p'
+ media_type=movie
++ printf %s 'The Platform (movie) [2019]	49941'
++ cut -f2
+ media_id=49941
+ '[' movie = tv ']'
+ keep_running=true
+ loop
+ '[' true = true ']'
+ get_embed
+ '[' movie = movie ']'
++ curl -s https://flixhq.to/ajax/movie/episodes/49941
++ sed ':a;N;$!ba;s/\n//g;s/class="nav-item"/\n/g'
++ sed -nE 's@.*href="([^"]*)"[[:space:]]*title="Vidcloud".*@\1@p'
+ movie_page=https://flixhq.to/watch-movie/watch-the-platform-49941.2361239
++ printf %s https://flixhq.to/watch-movie/watch-the-platform-49941.2361239
++ sed -nE 's_.*-([0-9]*)\.([0-9]*)$_\2_p'
+ episode_id=2361239
++ curl -s https://flixhq.to/ajax/sources/2361239
++ sed -nE 's_.*"link":"([^"]*)".*_\1_p'
+ embed_link='https://rabbitstream.net/v2/embed-4/9zHeh0dre7ze?z='
+ '[' -z 'https://rabbitstream.net/v2/embed-4/9zHeh0dre7ze?z=' ']'
+ '[' -z 'https://rabbitstream.net/v2/embed-4/9zHeh0dre7ze?z=' ']'
+ get_json
++ printf %s 'https://rabbitstream.net/v2/embed-4/9zHeh0dre7ze?z='
++ sed -nE 's_(.*)/embed-(4|6)/(.*)\?z=$_\1\t\2\t\3_p'
+ parse_embed='https://rabbitstream.net/v2	4	9zHeh0dre7ze'
++ printf %s 'https://rabbitstream.net/v2	4	9zHeh0dre7ze'
++ cut -f1
+ provider_link=https://rabbitstream.net/v2
++ printf %s 'https://rabbitstream.net/v2	4	9zHeh0dre7ze'
++ cut -f3
+ source_id=9zHeh0dre7ze
++ printf %s 'https://rabbitstream.net/v2	4	9zHeh0dre7ze'
++ cut -f2
+ embed_type=4
++ curl -s 'https://api.fffapifree.cam/get-source?id=9zHeh0dre7ze'
+ json_data='{"data":null,"message":"Too Many Requests, reason: Limit access free plan","warning":"Unlimited and high performance for just $160/month, Contact us Email: hqapiapp@gmail.com, Discord: freeapi","purchase_now":"https://fffapifree.cam"}'
+ '[' -n '{"data":null,"message":"Too Many Requests, reason: Limit access free plan","warning":"Unlimited and high performance for just $160/month, Contact us Email: hqapiapp@gmail.com, Discord: freeapi","purchase_now":"https://fffapifree.cam"}' ']'
+ extract_from_json
++ printf %s '{"data":null,"message":"Too Many Requests, reason: Limit access free plan","warning":"Unlimited and high performance for just $160/month, Contact us Email: hqapiapp@gmail.com, Discord: freeapi","purchase_now":"https://fffapifree.cam"}'
++ tr '[' '\n'
++ sed -nE 's@.*\\\"file\\\":\\\"(.*\.m3u8).*@\1@p'
++ head -1
+ video_link=
+ '[' -n '' ']'
+ '[' 0 = 1 ']'
++ printf %s '{"data":null,"message":"Too Many Requests, reason: Limit access free plan","warning":"Unlimited and high performance for just $160/month, Contact us Email: hqapiapp@gmail.com, Discord: freeapi","purchase_now":"https://fffapifree.cam"}'
++ tr '{}' '\n'
++ sed -nE 's@.*"file":"([^"]*)","label":"(.nglish)[,"\ ].*@\1@p'
+ subs_links=
+ subs_arg=--sub-file
++ printf %s ''
++ wc -l
+ num_subs=0
+ '[' 0 -gt 0 ']'
+ '[' -z '' ']'
+ send_notification 'No subtitles found'
+ '[' 0 = 1 ']'
+ '[' 0 = 0 ']'
+ '[' -z '' ']'
+ printf '\33[2K\r\033[1;34m%s\n\033[0m' 'No subtitles found'
No subtitles found
+ return
+ '[' -z '' ']'
+ exit 1

```

**Comment by SliceJosiah** [comment] 2024-04-08 08:28
I'm getting this too, it just shows 'No subtitles found' and then the video never plays.

**Comment by justchokingaround** [comment] 2024-04-08 08:51
duplicate of #196

**Closed** 2024-04-08 08:51 UTC

**Comment by justchokingaround** [comment] 2024-04-08 10:03
#193 i meant, sorry

**Comment by kengisenpai** [comment] 2024-04-09 16:40
I hope it will be get solved someday for sure and looing forward to it 
you and others and work harder for this and i appreciate your works

**Comment by kengisenpai** [comment] 2024-04-09 16:50
okey no issue take your time and all the best for your exams
