### ISSUE TITLE
When an episode ends, lobster increases seasons, not episodes

### ISSUE THREAD

**Issue by 097115** [justchokingaround/lobster#28] opened 2022-10-08 02:51 UTC
**Description:**

When an episode ends, the player quits, and you save your progress to history, lobster increases not the episode number in the history file but the season number.

**Steps to reproduce the behavior:**
1. Run lobster
2. Say, open 'Family Guy' season 3 episode 1
3. Fast forward to the end of the episode and just let it end and player quit
4. Press Enter to save episode progress
5. Press Enter to continue watching
6. Note that the suggested Family Guy history is season 4 episode 1, not season 3, episode 2

**Context:**
- OS: Ubuntu 
- Version: 7e1201c

**Comment by justchokingaround** [comment] 2022-10-08 02:54
duplicate of #27

**Closed** 2022-10-08 02:54 UTC
