### ISSUE TITLE
[bug] can't find certain video links

### ISSUE THREAD

**Issue by ghost** [justchokingaround/lobster#72] opened 2023-05-23 05:41 UTC
**Describe the bug**
i can't get some video links

**To Reproduce**
just try `lobster star treck deep space nine`
pick the first (star treck deep space nine tv)
you can't play any episode.

**Desktop (please complete the following information):**
 - OS: debian 11
 - Version 3.9.9

**Additional context**
It's probably related to the other error `[file] Cannot open file '': No such file or directory
Failed to open .`  A few commit earlier, it worked fine.

**Comment by justchokingaround** [comment] 2023-05-23 11:35
fixed in https://github.com/justchokingaround/lobster/commit/8caba4c88969ba097c36768521eae2a69c393b47

**Comment by justchokingaround** [comment] 2023-05-23 13:24
cannot reproduce:
![image](https://github.com/justchokingaround/lobster/assets/44473782/a797f26b-1053-40f0-b96a-3965d4b2728a)

did you set a preferred quality in the config file?

**Comment by justchokingaround** [comment] 2023-05-23 13:51
uh oh :skull: :skull: :skull: :skull: 
i pushed the changes

**Comment by justchokingaround** [comment] 2023-05-23 14:20
this is the commit i pushed https://github.com/justchokingaround/lobster/commit/5e99d3c8c8d78dfcd9f37bbb142d799fabfbdd3d, and i need opts for the resume feature, it should not be a problem for mpv

**Comment by justchokingaround** [comment] 2023-05-23 14:53
pushed in https://github.com/justchokingaround/lobster/commit/d76f1287aeb37f55582b43c18628987558193aab

**Closed as completed** 2023-05-23 15:09 UTC
