### ISSUE TITLE
[bug] play next episode with history=0

### ISSUE THREAD

**Issue by 097115** [justchokingaround/lobster#119] opened 2023-06-08 07:15 UTC
I'm probably missing something and I apologise in advance for that :)

**Is your feature request related to a problem? Please describe.**

When an episode of a TV show ends, `lobster` presents a user with a question and 3 possibilities: `Continue? 1. Yes 2. Exit 3. Search`

`Exit` obviously exits the program, and `Search` starts a new search. Now, the first option, `Yes`, could have continued playing the show, as it sounds. But it simply restarts the previously played episode :)

**Describe the solution you'd like**

Wouldn't it be more logical to play the **next** episode if a user answers `Yes`? Probably incrementing the episode number somewhere after the question and before starting the playback? 

**Additional context**

Also, it would be extremely great if that continuous playback would somehow happen automatically. Like, a user launches `lobster`, selects a show and a starting episode, and then it just plays one episode after another without any additional questions until a user cancels it specifically. But that would probably be a bit cumbersome to implement, since `lobster` would need to distinguish between the expected episode end and the intended player exit...

**Comment by justchokingaround** [comment] 2023-06-08 07:23
no need to apologize. right now `lobster` does play the next episode when you choose the `Yes` option, but you need history to be enabled for it to work (`history=1` in the config). it is a bug that it does not work by default, with history disabled, i will fix that. the problem with the binge watching approach is: how does the script know when a user wants to stop watching the show? is he just expected to spam `Ctrl-c` ?

**Comment by justchokingaround** [comment] 2023-06-08 07:37
> Yeah, agreed, mentioned that in the original post, too. With mpv, you can make a binding to exit with a custom exit code (and lobster could analyze that)

the problem is that although mpv is the preferred player and the one that supports the most features for `lobster`, it would be a bit cumbersome to implement this exit code stuff, since other players don't all have that

> Thank you again! (And you will probably close this when the fix you mentioned will be available?)

yes

**Comment by justchokingaround** [comment] 2023-06-13 13:44
This should be fixed in https://github.com/justchokingaround/lobster/commit/d707a1aaf523b11a47cf64efaf8bb2eb9d1ecffe (currently only on the `fix-subs` branch)

**Comment by 097115** [comment] 2023-06-14 02:52
> This should be fixed 

Indeed, it is! Thanks :)

**Comment by justchokingaround** [comment] 2023-06-18 09:20
fixed and merged in 0f22bad6cba1c890fc8808f468eb053be40b011c

**Closed by justchokingaround** 2023-06-18 09:20 UTC
Labels: bug
