### ISSUE TITLE
Notification that selected movie/tv show is loading.... or streaming...

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#109] opened 2023-06-01 15:29 UTC
![1](https://github.com/justchokingaround/lobster/assets/95531944/b400a357-bdcb-4c60-a5a4-57f558128369)
![2](https://github.com/justchokingaround/lobster/assets/95531944/27ec1b1b-5c0d-4d81-a5c9-4536da291612)

**Comment by justchokingaround** [comment] 2023-06-06 06:01
please update to the latest version, and send me the logs, i cannot reproduce this behavior, it works fine for me:
![image](https://github.com/justchokingaround/lobster/assets/44473782/108de2f5-d96d-40d4-bee9-be256f7c9677)

**Comment by ttx99** [comment] 2023-06-06 06:58
do I run it like lobster -x sisu? where do i find the log file again?

**Comment by justchokingaround** [comment] 2023-06-06 06:59
`lobster -x -r` and the log file is in `/tmp/lobster.log`

**Comment by ttx99** [comment] 2023-06-06 07:02
[lobster.log](https://github.com/justchokingaround/lobster/files/11660973/lobster.log)

**Comment by justchokingaround** [comment] 2023-06-06 07:03
that's the log from when u updated the script

**Comment by ttx99** [comment] 2023-06-06 07:07
[lobster.log](https://github.com/justchokingaround/lobster/files/11661026/lobster.log)

**Comment by justchokingaround** [comment] 2023-06-06 07:07
same file

**Comment by ttx99** [comment] 2023-06-06 07:08
do i need to stop watching the video for it to be written on the log?

**Comment by justchokingaround** [comment] 2023-06-06 07:10
here is mine for this command, as an example (the command being `lobster -x -r`

[lobster.log](https://github.com/justchokingaround/lobster/files/11661040/lobster.log)

**Comment by justchokingaround** [comment] 2023-06-06 07:10
> do i need to stop watching the video for it to be written on the log?

no, u don't

**Comment by ttx99** [comment] 2023-06-06 07:12
cause thats all i can find

**Comment by ttx99** [comment] 2023-06-06 07:14
![1](https://github.com/justchokingaround/lobster/assets/95531944/37d0c804-6081-451b-96bb-afa8d0e966c4)
![2](https://github.com/justchokingaround/lobster/assets/95531944/cf1e6eaa-2b5c-4683-a3e5-da72ee309546)

**Comment by ttx99** [comment] 2023-06-06 07:16
history=0
use_external_menu=0
image_preview=0
image_config_path="$HOME/.config/rofi/styles/launcher.rasi"
subs_language="English"
player="mpv"
json_output=0
histfile="$HOME/.local/share/lobster_history.txt"
cache_dir="/tmp/lobster"
images_cache_dir="/tmp/lobster-images"
applications_dir="$HOME/.local/share/applications/lobster"
tmp_position="/tmp/lobster_position"
lobster_editor=lite-xl

**Comment by justchokingaround** [comment] 2023-06-06 07:21
try running `rm /tmp/lobster.log` and then running the `lobster -x -r` command again. if the log file is still the same, then try running `sh -x $(command -v lobster) -x -r 2>log` and send that log here (it will be in the current working directory)

**Comment by ttx99** [comment] 2023-06-06 07:24
[lobster.log](https://github.com/justchokingaround/lobster/files/11661149/lobster.log)

**Comment by ttx99** [comment] 2023-06-06 07:33
![1](https://github.com/justchokingaround/lobster/assets/95531944/c1de932d-6534-49d8-9355-ac91a2b6053c)

**Comment by justchokingaround** [comment] 2023-06-06 07:36
please send the log

**Comment by ttx99** [comment] 2023-06-06 07:40
[lobster.log](https://github.com/justchokingaround/lobster/files/11661293/lobster.log)

**Comment by justchokingaround** [comment] 2023-06-06 07:43
663c8a4 fixes it, i forgot to add a return statement

**Comment by ttx99** [comment] 2023-06-06 07:49
![1](https://github.com/justchokingaround/lobster/assets/95531944/534228ef-81e6-4b18-9185-3ff7e3c8d0ba)

**Comment by ttx99** [comment] 2023-06-06 07:52
![2](https://github.com/justchokingaround/lobster/assets/95531944/24dfd171-4107-4351-9bd7-264e1a7b0841)

**Comment by justchokingaround** [comment] 2023-06-06 07:57
i um, forgot to run `git push`, works now, sorry about that (it displays that the commit was done 13 mins ago, but that's when i committed it locally, not when i pushed)

**Comment by ttx99** [comment] 2023-06-06 08:04
![1](https://github.com/justchokingaround/lobster/assets/95531944/48b7e3af-b139-4d13-a2e9-0d95be911b0a)

**Comment by justchokingaround** [comment] 2023-06-06 08:18
is this not expected behavior? what is the meaning of that screenshot?

**Comment by ttx99** [comment] 2023-06-06 08:19
i mean its works sorry

**Closed** 2023-06-06 08:19 UTC
Labels: enhancement
