### ISSUE TITLE
[bug]: fails to get video links

### ISSUE THREAD

**Issue by 1bn3mar** [justchokingaround/lobster#193] opened 2024-02-29 19:49 UTC
**IDKy but the script just refused to work for me*
I'm using macOS and mpv as my media player i didn't do anything special.

**For me what happened was i just followed the installation process then tried to watch a show**
1. $ lobster <show>
2. specify which show exactly season & episode etc.
3. then it just outputs this: gsed: -e expression #1, char 0: no previous regular expression
No subtitles found

P.S. this happens for anything i try to watch.
[lobster.log](https://github.com/justchokingaround/lobster/files/14452853/lobster.log)

**Comment by 1bn3mar** [comment] 2024-02-29 19:52
This is the output 
gsed: -e expression #1, char 0: no previous regular expression
No subtitles found

**Comment by masoniis** [comment] 2024-02-29 20:52
For what it's worth, I am new to the script as well and I run into the same issue on NixOS and MacOS. For NixOS I am using the flake, and here is what it looks like running the command:
```
> lobster
Search Movie/TV Show: rick and morty
sed: -e expression #1, char 0: no previous regular expression
No subtitles found
```

**Comment by justchokingaround** [comment] 2024-02-29 20:54
```sh
curl -s "https://keys4.fun" | tr -d '\n ' | sed -nE "s@.*\"rabbitstream\":\{\"keys\":\{\"v\":\"([^\"]*)\",\"h\":\"([^\"]*)\",\"b\":([0-9]*),\"agent\":\"([^\"]*)\",\"key\":\"([^\"]*)\".*@\1\t\2\t\3\t\4\t\5@p" | read -r v h b agent key

https://rabbitstream.net/ajax/v2/embed-4/getSources?id={}&v={}&h={}&b={}
```

rabbitstream changed their encryption
above is the fix in question, which i'll do soon :tm:

**Comment by LuisOrg26** [comment] 2024-03-01 20:20
> rabbitstream changed their encryption above is the fix in question, which I'll do soon ™️
Hi does this works with windows too? I'm new in this and the command doesn't worked for me

**Comment by justchokingaround** [comment] 2024-03-01 20:25
that was just some pseudo code, ure supposed to replace `{}` with the actual values

**Comment by SushiDTubarao** [comment] 2024-03-02 00:11
Wait, here's my log the variable json_data output an html document for some reason?
[lobster.log](https://github.com/justchokingaround/lobster/files/14467080/lobster.log)

**Comment by justchokingaround** [comment] 2024-03-02 00:14
yes, that is normal. also the encryption has changed again since my previous comment, so i need to wait for keys4.fun to update their stuff or look for another fix

**Comment by justchokingaround** [comment] 2024-03-02 12:19
i prefer avoiding additional unneeded deps

**Comment by pitsi** [comment] 2024-03-04 10:38
During the weekend, I tried patching the script using jq to get the key parameters and add them to the fake url above. It failed with the same error as before.

And today I saw how a kodi addon was patched so as to work again with the new decryption method. Oh my....

**Comment by justchokingaround** [comment] 2024-03-04 22:03
corresponding values u can find on https://keys4.fun , tho its broken rn

**Comment by 1bn3mar** [comment] 2024-03-04 22:48
So, ur saying there's noway to use `lobster` rn?

**Comment by pitsi** [comment] 2024-03-05 06:46
@1bn3mar 
I made 3 new variables, as you can see below, which get keys v, h and b like so (replace the letters as needed)
`keyb=$(curl -s https://keys4.fun | jq .rabbitstream.keys.b)`
and I changed the json_data variable to this
`json_data=$(curl -s "${provider_link}/ajax/embed-${embed_type}/getSources?id=${source_id}"&v={keyv}&h={keyh}&b={keyb}-H "X-Requested-With: XMLHttpRequest")`
but it fails with the same error, so it needs something else to be changed too.

@justchokingaround 
Do we need all those keys? A while ago, the script was grabbing 2 16-character long strings only as keys.

**Comment by pitsi** [comment] 2024-03-05 10:09
I see... I will try it again when I have some time.

As for the kodi addon, there is no commit for it, because the "change" is always a zip file that gets uploaded. But if you want, I can download both (old and new) and create a .patch file from them.
If not, I can just mention the addon and the dev and you get them from his repo.

**Comment by justchokingaround** [comment] 2024-03-05 10:10
the patch would be enough thx

**Comment by pitsi** [comment] 2024-03-05 10:16
https://paste.debian.net/hidden/39332f7a/

Paste will be available for 7 days,

**Comment by justchokingaround** [comment] 2024-03-05 10:21
thx i'll check it today

**Comment by justchokingaround** [comment] 2024-03-05 11:39
@pitsi can u actually mention the repo pls?

**Comment by pitsi** [comment] 2024-03-05 13:13
https://github.com/mbebe/blomqvist/tree/master/zips/plugin.video.fmoviesto

Version 1.30 is the new one that works.

**Comment by 1bn3mar** [comment] 2024-03-09 04:54
@pitsi Yeah, to me this is a real brain teaser I'm no programmer by any means; I just don't know how to get the keys.

**Comment by pitsi** [comment] 2024-03-09 10:14
What do you want me to explain? 
Tbh, it has been so many days since the real issue and new keys were found, but there is still no fix for it, so maybe rabbitstream is doing a great work protecting its links. I hope this won't mean the end of lobster :(

**Comment by justchokingaround** [comment] 2024-03-09 10:17
it's not the end. i'm just a bit busy at work atm, so i don't have time to reverse engineer everything and can only port an existing solution or use keys that would be updated regularly by someone. i looked at the python code and the problem is all of the decryption is done in it, it doesnt rely on any key provider. porting that to shell would take me more time than i have atm

**Comment by pitsi** [comment] 2024-03-09 11:02
But there is a key (provider?) in that python code, at the variable named klucze.

**Comment by 1bn3mar** [comment] 2024-03-14 11:25
In conclusion `lobster` does not work rn unless the user tinkers with it; if yes I'll just close the issue if not can someone please give me a oneliner to run or a preconfigured file to replace mine cuz if not I'll keep the question's coming.

PS: i don't get notified that's why i take too long.

**Comment by justchokingaround** [comment] 2024-03-14 11:33
it's broken on my side not the user's. i should be able to come up with a fix soon tm

**Comment by pitsi** [comment] 2024-03-14 12:28
What do you mean "tinkers with it"? What can be changed?

**Comment by 1bn3mar** [comment] 2024-03-14 12:30
@pitsi I mean the whole conversation between you and @justchokingaround i did not get one bit of it.

**Comment by pitsi** [comment] 2024-03-14 12:43
I can explain stuff that you may not understand, but some basic knowledge is required first. 
For instance, I can not explain WHY things have to be decrypted for the script to work.

**Comment by 1bn3mar** [comment] 2024-03-14 13:03
Like what is `provider_link`, `embed_type`, `source_id`, `keyv`, `keyh`, `keyb` should replace them with something or just leave them as is?

**Comment by pitsi** [comment] 2024-03-14 13:57
Let me explain some stuff then...

Before I start, I want to say that my bash skills are not as good as the dev's, which is why I suggested jq. It is a small parsing app that helps people like me who do not understand sed and the like.

The scipt's core function is to get a very specific url and pass it to the player. In order to do so, it has to do some decrypting, because things are not as easy as they were a few months ago. In short, it has to use a url that looks like this
`https://rabbitstream.net/ajax/v2/embed-4/getSources?id={}&v={}&h={}&b={}`
The id part is something that uniquely identifies the movie (or whatever you want to see), e.g for deadpool it's always 19694. 
The parameters (or keys) v, h, and b are stuff that changes MANY times per day and everytime the script is run, they are parsed fresh from a specific url. This was always the case though, but there were only 2 keys a few weeks ago.

In order for me to test the new way, I had to create 3 new variables for the keys and add them to the url above. That is where I used jq. However, they are not enough, because the script still fails (proof in the log). I also tried adding the user agent, but still no luck. As it seems, the whole thing is still incomplete, and I have no idea what to do next. 

Any other questions?

**Comment by justchokingaround** [comment] 2024-03-14 14:07
the keys are ip specific now i'm pretty sure, ill look into it soon

**Comment by 1bn3mar** [comment] 2024-03-14 14:19
No, so far so good now i don't feel brainless thank you.

**Comment by pitsi** [comment] 2024-03-16 11:08
Honest question: is there any chance that the keys provided by keys4fun are wrong?

**Comment by justchokingaround** [comment] 2024-03-16 11:09
yes

**Comment by pitsi** [comment] 2024-03-16 12:59
The following may be offtopic for lobster's development, but I want to mention it anyway.

One of the things that have annoyed me today is that the forementioned kodi addon broke. Again. Because the keys it uses to decode the urls are not working or wrong. Αgain. 

So I though "why not try the keys from the url lobster uses?" and obviously the ones mentioned for fmovies. With my basic knowledge of python I patched its code and made it retrieve the correct ones. But it still failed. Then I had an... Archimedes* moment: what if it needs the keys for mycloud? 
I patched its code again, making it retrieve the keys for vidcloud and poof! It worked first try!

How can lobster be changed so as to use those 2 keys, like it used to be?

* According to a rumor, when Archimedes was about to discover the laws for buoyancy, he was lost in his calculations and a "I may be in a wrong path" thought crossed his mind. So he started over, did his calculations again and this time they worked. The rest is what you learned from the history books :)

**Comment by justchokingaround** [comment] 2024-03-16 13:05
lemme explain it the KISS way:

flixhq != fmovies

think of flixhq as an equivalent of hianime (ex aniwatch and ex zoro)
think of fmovies as an equivalent of aniwave (ex 9anime)

flixhq uses vidcloud and upcloud which are basically rabbitstream e4
fmovies uses vidplay and mycloud, which use different encryption mechanisms

to adapt lobster to use fmovies instead of flixhq, a lot of code would have to be added, history would need to be changed etc. (u can see here an example of what it's like to implement a new provider, even though i never finished it: https://github.com/justchokingaround/lobster/pull/135/files)

if u're curious about the js functions used for decryption or encryption (e.g futoken), u can check the following link (some functions may be outdated): https://keys4.fun/decrypt.js

**Comment by pitsi** [comment] 2024-03-16 13:10
I only knew half of that, thank you for enlightening me! Also, the hosts' names confuse me a lot!

I do not want you (or anyone) to rewrite lobster for fmovies, my suggestion was only for the hosts. But since they differ, its no use discussing anything else.

**Comment by mesteryui** [comment] 2024-03-16 20:59
I have similar problems this is my output with lobster:
I have my system in spanish but by the things that are saying I think is the same error
`sed: -e expresión #1, carácter 0: no hay una expresión regular previa`

**Comment by pitsi** [comment] 2024-03-17 12:00
> the keys are ip specific now i'm pretty sure, ill look into it soon

About that, episode 2. My stupid brain thought that the keys **offered by** the site differ if you visit it from another ip, which is wrong. What differs are the `generated` keys themselves, because they were gennerated for that site's ip when the javascritp file ran. So, is there any way to run that js file and get "personal" keys from it? Without resorting to node if possible.

**Comment by justchokingaround** [comment] 2024-03-20 18:30
[fix: rabbitstream tmp solution](https://github.com/justchokingaround/lobster/commit/e513c273560b380a868244869efc82eb985a7530) acts as a temporary fix

**Comment by pitsi** [comment] 2024-03-21 04:49
It works for me now... on that 7am test I just did :D
Thank you :)

**Comment by pitsi** [comment] 2024-03-21 17:18
May I ask why the fix is named/marked as "temporary solution"?

**Comment by justchokingaround** [comment] 2024-03-21 18:38
bc idk who is hosting `        json_data=$(curl -s "https://api.fffapifree.cam/get-source?id=${source_id}")` and idk when it might go down

**Comment by pitsi** [comment] 2024-03-24 10:01
Aaand it's broken again. Although I did not test it the days before, I tried it today and it playes this url (no matter what the user has searched or selected)
`https://api.fffapifree.cam/video/filename.m3u8`
which is a 5 second video of a single frame that says "please purchase etc".

It was good as long as it lasted :(

**Comment by stillmanpeeer** [comment] 2024-03-27 00:52
> Aaand it's broken again. Although I did not test it the days before, I tried it today and it playes this url (no matter what the user has searched or selected) `https://api.fffapifree.cam/video/filename.m3u8` which is a 5 second video of a single frame that says "please purchase etc".
> 
> It was good as long as it lasted :(

https://github.com/stillmanpeeer/rabbitstream

**Comment by pitsi** [comment] 2024-03-27 04:56
Leaving aside that lobster works, at least for today and on my end, I just noticed that you are the dev of the project.
Are you advertising it or are you asking for any bug reports to be made there? Please be more accurate.

**Comment by stillmanpeeer** [comment] 2024-03-27 12:36
sorry my bad, because the cost is limited, I have to limit my daily use of this API. Because there are so many users, I encountered this problem.

**Comment by justchokingaround** [comment] 2024-03-27 12:48
do u see statistics about where most requests are coming from

**Comment by pitsi** [comment] 2024-03-27 12:56
I am ok with that, as long as you mention it somewhere.

p.s. I am talking as an angry user of other apis which lowered (or even eliminated) their access limits without any notice, ever.

**Comment by stillmanpeeer** [comment] 2024-03-27 18:19
> do u see statistics about where most requests are coming from

mostly from vercel application.

**Comment by stillmanpeeer** [comment] 2024-03-27 18:21
> I am ok with that, as long as you mention it somewhere.
> 
> p.s. I am talking as an angry user of other apis which lowered (or even eliminated) their access limits without any notice, ever.



> I am ok with that, as long as you mention it somewhere.
> 
> p.s. I am talking as an angry user of other apis which lowered (or even eliminated) their access limits without any notice, ever.

Yes, I will write down the information clearly

**Comment by justchokingaround** [comment] 2024-03-27 18:58
if ure willing to share the code (it can stay closed source, i don't mind that, i actually prefer it that way) with me, i might be able to find a hosting solution from someone in the discord server

**Comment by pitsi** [comment] 2024-04-03 15:53
Guess what happened...

After 1+ week of not touching it at all (because I have nothing to watch these days), I launched lobster today to test it. And it simply fails, because, as you can see in the log below, the api it now uses has blocked access due to too many requests!
https://paste.debian.net/hidden/7fc3cc0a/

If the api's dev (@stillmanpeeer) is reading this, please explain how I managed to pass the 5000 requests/day limit that you have set (assuming that the limit is indeed at 5000 requests and not lower or zero), when lobster called it ONCE (or maybe 4 times as you can see in the log) in order to work. 
I am asking it as an angry user of youtube's api, which "charges" 1 api call per 1 video view, but a single search "costs" 100 api calls. And all that with its daily limit being at 10000 calls!

In other news, keys4fun (the domain) shut down last week and its dev's account here on github gets to a 404 today, so things are now pretty bleak for lobster :(

**Comment by Dragon-Batch** [comment] 2024-04-07 10:21
anyone got a decryption method for /v2/embed-4/ player?

**Comment by justchokingaround** [comment] 2024-04-07 10:41
techincally yes, but i cant open source it

**Comment by Dragon-Batch** [comment] 2024-04-07 20:54
> techincally yes, but i cant open source it

i have a handful of questions that have just been scratching that part of my brain for a while. if you dont mind answering even just a few i would be greatful :3 :3 :3 :3 :3 :3 :3

1. is it available as an api or something? if so, will it cost money to use? i need it to rip all content from flixhq as i have found a *method* of obtaining free storage space.

2. why do the providers keep changing the encryption? it just keeps getting cracked so i dont see the point in changing it if its gonna get destroyed anyway.

3. do we know if there is a known api endpoint that these sort of providers use to communicate/generate links for the stream url hosts? because the urls for each stream link are different when decrypted again and again (i think) and not returning a duplicate one so they must be generating them somehow.

4. do we know how they store the video segments? do they just have a gigachad storage method or are they using something like mass generated google drive accounts with the entire 15GB free storage used.

5. do we know the owners of the providers? do they have contact information available to the public?

6. are the providers just really shit at coding because (this community) is breaking their decryption so easily (it seems).

7. some of the videos are encoded with AV1 and that is a pretty serious codec, it requires both good hardware and fine tuning. how do the providers compress the videos so quickly? it seems they add new stuff every day!!!

8. why are some of the m3u8 playlists you get from some of the providers corrupt? "segments" returning 404 & 502 errors. is there a way to stop this from happening? i have included my own checking and just skipping the videos that dont match within 5 seconds of the playlists supposed length and the mp4 file.

9. how do the providers stay up for so long? particularly rabbitstream as their website just looks like a normal video streaming service but given the knowledge of that it does, it just looks like a "front" for piracy. how have the servers not been raided by the fbi or like a swat team or something???

10. is there a better alternative to flixhq in terms of crackability and larger selection of videos? you can see the list of movies and series on said website if you goto /sitemap.xml, as this will have a bunch of xml pages that follow something to this format: sitemap-list-[0-.1.2.3..].xml. different providers and stuff.

**Comment by Ciarands** [comment] 2024-04-07 23:03
@Dragon-Batch 
A fair few questions lol but ill answer some for you
1. Chomsky is talking about something I was working on, I haven't turned it into an API yet just because busy with life, there is no API that I am aware of currently though.
2. Saves them money I'd guess, take us @ movie-web for instance, we probably cost them a bit of money just with our users, and we're not serving ads for them, there's certainly reason to want to quickly break stuff, however they're not super creative, best src I've seen so far is flixhq, but even they're kinda trivial to scrape due to some major oversights on their behalf.
3. Not that I'm aware of?
4. It depends on the provider, many host on DMCA ignored VPS's, its really not that expensive and they're making a fair bit of money.
5. No, we don't scrape sites that we know the owners of usually lol.
6. Its not that they're shit at coding, its that its very difficult to come up with a creative sln to stop us due to the nature of the web, I can think of a few methods that would stop 99% of scrapers, but all it takes is 1 person to break it.

**Comment by Dragon-Batch** [comment] 2024-04-08 06:21
@Ciarands if you want, i guess i consider my self experienced at making apis with flask in python so i think i could help you make one if you want :33

**Comment by triorr** [comment] 2024-04-26 02:24
The key is generated inside a web assembly module disguised as a PNG image in "loading.png". Reverse engineering skills is needed to fix this script.
For more info check this article https://www.pudn.com/Download/item/id/1711319547629731.html

**Comment by luvcie** [comment] 2024-04-26 02:45
> https://github.com/stillmanpeeer/rabbitstream
Could you be more specific on what is this?

**Comment by Dragon-Batch** [comment] 2024-04-26 14:23
its a advertisement to some shity api that costs 160$/month

**Comment by pitsi** [comment] 2024-04-27 09:24
Although I disagree with the price asked for accessing the api, because its a lot for a single user who will use it. and with its lack of documentation, especially about the requests per day limit, I have to admit that the api works. 
When lobster was first patched so as to use it, it did return steams and subtitles for them, so yea, it does work as intended.

**Comment by justchokingaround** [comment] 2024-04-30 21:41
![image](https://github.com/justchokingaround/lobster/assets/44473782/cf8e1eb3-d1d4-4714-951e-2b396f51fb4c)

so i'm currently implementing a vidsrc scraper to switch over to it from rabbitstream. if anyone has ever implemented rc4 decryption using openssl pls hmu, bc porting my bash code to posix shell, without using arrays is gonna be a bit painful

**Comment by pitsi** [comment] 2024-05-01 05:22
All this is what must be done for getting the keys? If so, I may know a github repo that generates them.
How can I contact you though? I am not on matrix and neither on known and unknown social  media.

**Comment by justchokingaround** [comment] 2024-05-01 09:30
@chomkerman:matrix.org

**Comment by pitsi** [comment] 2024-05-01 09:40
Yes, I know that, it's on your profile's info.
I am not on matrix. I also do not make accounts here and there.

**Comment by justchokingaround** [comment] 2024-05-01 09:42
oh sorry i thought i said u are on matrix, my bad

**Comment by pitsi** [comment] 2024-05-01 10:08
So the problem is that gibberish on the url, like %3A and %2F, we see on the right terminal?

**Comment by justchokingaround** [comment] 2024-05-01 10:35
no, the problem is that the decryption code i wrote is bash specific and not posix compliant, since i use an array for `S`

**Comment by pitsi** [comment] 2024-05-01 12:13
Sorry, I can't help you with that :(

**Comment by triorr** [comment] 2024-05-01 15:36
@justchokingaround Try something like this

```bash
echo -n "yB5_gMJfMGtHJCTb6P4aLZpbJu9hxhicEj==" | sed 's/_/\//g' | sed 's/-/+/g' | base64 -d | openssl rc4 -K $(echo -n "WXrUARXb1aDLaZjI" | xxd -p | tr -d '\n') -nopad

```

**Comment by justchokingaround** [comment] 2024-05-01 15:42
![image](https://github.com/justchokingaround/lobster/assets/44473782/bbb1a07f-7a52-4518-80b6-77d33d1992ee)
did you generate this using AI ? did this work when u ran it on ur system?

i've tried getting rc4 to work using openssl but couldn't, even with my experience with it. i need someone who has actually done it before and got it working.

also `echo -n` isn't posix compliant, you should use `printf` instead, it doesnt output a newline by default

**Comment by triorr** [comment] 2024-05-01 19:21
@justchokingaround Sorry. I'm not very familiar with POSIX compliance.
I have tested this on bash, sh, zsh and even fish they all work for me with "echo -n" and "printf".
Try adding the commands one by one to check whats wrong.
First your base64 has a problem with that input try the full base64 url from vidsrc. Because I cut it down for readability and it worked on my machine. 
About openssl I think you have the legacy algorithms disabled for security reasons check with this:
```sh
$ openssl list -providers
Providers:
  default
    name: OpenSSL Default Provider
    version: 3.2.1
    status: active
  legacy
    name: OpenSSL Legacy Provider
    version: 3.2.1
    status: active

```
to activate the legacy algorithms you need to add/uncomment these lines 
```
legacy = legacy_sect

[legacy_sect]
activate = 1

[default_sect]
activate = 1
```
in your /etc/ssl/openssl.cnf

**Comment by justchokingaround** [comment] 2024-05-01 19:30
okay thanks a lot, i'll check it later

**Comment by justchokingaround** [comment] 2024-05-01 21:44
that worked just fine, thank you a lot @triorr for helping me figure out that the problem was the openssl package i was using (i just changed from openssl to openssl_legacy on nix)
```sh
printf "%s" "$url" | sed "s/_/\//g;s/-/+/g" | base64 -d | openssl rc4 -K "$(printf "%s" "$key" | xxd -p)" -nopad
```

**Comment by Kat299** [comment] 2024-05-24 06:46
> Guess what happened...
> 
> After 1+ week of not touching it at all (because I have nothing to watch these days), I launched lobster today to test it. And it simply fails, because, as you can see in the log below, the api it now uses has blocked access due to too many requests! https://paste.debian.net/hidden/7fc3cc0a/
> 
> If the api's dev (@stillmanpeeer) is reading this, please explain how I managed to pass the 5000 requests/day limit that you have set (assuming that the limit is indeed at 5000 requests and not lower or zero), when lobster called it ONCE (or maybe 4 times as you can see in the log) in order to work. I am asking it as an angry user of youtube's api, which "charges" 1 api call per 1 video view, but a single search "costs" 100 api calls. And all that with its daily limit being at 10000 calls!
> 
> In other news, keys4fun (the domain) shut down last week and its dev's account here on github gets to a 404 today, so things are now pretty bleak for lobster :(

Yep, that's happening for me too.

**Comment by justchokingaround** [comment] 2024-05-28 03:16
dd205d91b703df3d6d41a6d617c96a35a45d42b7

**Closed by justchokingaround** 2024-05-28 03:16 UTC
