### ISSUE TITLE
"No Links Found" in every query, Even for the histories

### ISSUE THREAD

**Issue by EnigmaticJihad** [justchokingaround/lobster#21] opened 2022-09-18 05:36 UTC
**Describe the bug**
It started yesterday I guess. When I was trying to play "_The Phantom Menace_". It just showed `No links found`. I assumed it was an old movie. So after a while, I tried another. Same. Then I tried some from the history with `lobster -c`, and the same issues again. Tired of upgrading the system programs, assuming some dependency fault. Update the actual scripts through `lobster -u`. Totally removed and reinstall again. Nothing works. Lobster is now my fav movie/tv watching method. So, I'm pretty down.

**To Reproduce**
1. Type lobster in the terminal
2. enter a search query
3. select from the options
4. Here's the error

**Expected behavior**
I just expect the script to work.

**Screenshots**
[screenshot](http://0x0.st/oVsU.png)

**Desktop (please complete the following information):**
 - **OS**: Gentoo
 - **Browser**: Brave
 - **Browser Version**: 1.43.93
 - **Lobster Version**: 2.0.2

**Comment by justchokingaround** [comment] 2022-09-18 05:55
the problem is that now video links are encrypted and i need to implement decryption which i haven't had a lot of time to do yet. i'll look further into it today, here's a ressource i've saved for later https://github.com/recloudstream/cloudstream-extensions/blob/95c9aba1c23b4db8ea83e50b5134dff408979f27/SflixProvider/src/main/kotlin/com/lagradost/SflixProvider.kt#L715-L722

**Comment by justchokingaround** [comment] 2022-10-02 12:36
fixed in 32841b4d710a5e6d85ecbe3ccb699e8ddb9e97be

**Comment by olivluca** [comment] 2022-10-02 21:11
Not really

```
$ lobster -v
Lobster version: 3.0.1
$ lobster stranger things
Loading...
Please choose a season number between 1 and 4: 4
Please choose an episode number between 1 and 9: 8
No links found
$ lobster severance
Loading...
Please choose an episode number between 1 and 9: 1
No links found
```

**Comment by justchokingaround** [comment] 2022-10-02 21:21
does 
```sh
curl "https://api.consumet.org/movies/flixhq/watch?episodeId=1168337&mediaId=tv/watch-vincenzo-67955"
```
work for u?

**Comment by olivluca** [comment] 2022-10-02 21:43
Yes, but:

```
$ lobster vincenzo
Loading...
Please choose an episode number between 1 and 20: 1
No links found

```

**Comment by justchokingaround** [comment] 2022-10-03 01:48
https://flixhq.to/watch-tv/watch-vincenzo-67955.4829542
check if the website works for you

**Comment by olivluca** [comment] 2022-10-03 06:34
The site works, lobster still says "no links found".

**Comment by justchokingaround** [comment] 2022-10-03 11:36
if this happens with every tv show/movie can u send me the output of 
```sh
sh -x $(which lobster) fight club
```
(after u select the first choice)

**Comment by olivluca** [comment] 2022-10-03 13:55
```
$ sh -x $(which lobster) fight club
+ version=3.0.1
+ base=https://api.consumet.org/movies/flixhq
+ config_file=/home/luca/.config/lobster/lobster_config.txt
+ history_file=/home/luca/.config/lobster/lobster_history.txt
+ '[' '!' -d /home/luca/.config/lobster ']'
+ '[' '!' -f /home/luca/.config/lobster/lobster_config.txt ']'
++ grep '^player=' /home/luca/.config/lobster/lobster_config.txt
++ cut -d= -f2
+ player=
++ grep '^subs_language=' /home/luca/.config/lobster/lobster_config.txt
++ cut -d= -f2
+ subs_language=English
++ grep '^video_quality=' /home/luca/.config/lobster/lobster_config.txt
++ cut -d= -f2
+ video_quality=
++ grep '^preferred_server=' /home/luca/.config/lobster/lobster_config.txt
++ cut -d= -f2
+ server=
+ case "$(uname -s)" in
++ uname -s
+ separator=:
+ path_thing='\'
+ getopts cduUvVh opt
+ '[' -z '' ']'
+ get_input 'fight club'
+ '[' -z 'fight club' ']'
+ query='fight club'
++ printf %s 'fight club'
++ tr ' ' -
+ query=fight-club
++ curl -s https://api.consumet.org/movies/flixhq/fight-club
++ fzf --border -1 --reverse --height=12 --with-nth 2..
++ sed -nE 's@"id":"([^"]*)","title":"([^"]*)",.*"type":"([a-zA-Z ]*)"$@\1\t\2 (\3)@p'
++ tr '{|}' '\n'
+ movies_choice='movie/watch-fight-club-19651   Fight Club (Movie)'
+ '[' -z 'movie/watch-fight-club-19651  Fight Club (Movie)' ']'
++ sed -nE 's_.*\(([a-zA-Z ]*)\)$_\1_p'
++ printf %s 'movie/watch-fight-club-19651      Fight Club (Movie)'
+ media_type=Movie
++ printf %s 'movie/watch-fight-club-19651      Fight Club (Movie)'
++ cut -f1
+ media_id=movie/watch-fight-club-19651
++ printf %s 'movie/watch-fight-club-19651      Fight Club (Movie)'
++ cut -f2
++ sed -nE 's_(.*) \((.*)\)$_\1_p'
+ movie_title='Fight Club'
+ main
+ printf 'Loading...\n'
Loading...
+ case "$media_type" in
++ curl -s 'https://api.consumet.org/movies/flixhq/info?id=movie/watch-fight-club-19651'
++ tr '{|}' '\n'
++ sed -nE 's@"id":"([0-9]*)".*@\1@p'
+ episode_id=19651
+ video_title='Fight Club'
+ play_video
++ curl -s 'https://api.consumet.org/movies/flixhq/watch?episodeId=19651&mediaId=movie/watch-fight-club-19651&server=&'
+ json_data='{"message":"Media Not found."}'
++ printf %s '{"message":"Media Not found."}'
++ tr '{|}' '\n'
++ sed -nE 's@"Referer":"([^"]*)"@\1@p'
+ referrer=
++ printf %s '{"message":"Media Not found."}'
++ tr '{|}' '\n'
++ sed -nE 's@"url":"([^"]*)","quality":"",.*@\1@p'
+ mpv_link=
++ printf %s '{"message":"Media Not found."}'
++ tr '{|}' '\n'
++ sed -nE 's@"url":"([^"]*.vtt)","lang":"English.*@\1@p'
++ sed -e 's/:/\\:/g' -e 'H;1h;$!d;x;y/\n/:/' -e 's/:$//'
+ subs_links=
+ '[' -z '' ']'
+ printf 'No links found\n'
No links found
+ exit 1

```

This is the json returned by the second curl call ( `curl "https://api.consumet.org/movies/flixhq/info?id=movie/watch-fight-club-19651" | jq`):

```
{
  "id": "movie/watch-fight-club-19651",
  "title": "Fight Club",
  "url": "https://flixhq.to/movie/watch-fight-club-19651",
  "image": "https://img.flixhq.to/xxrz/250x400/379/c8/67/c867cdf6d0a0683fa88ada21ec51671a/c867cdf6d0a0683fa88ada21ec51671a.jpg",
  "description": "\n        A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground \"fight clubs\" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.\n    ",
  "type": "Movie",
  "releaseDate": "1999-10-15",
  "genres": [
    "Drama"
  ],
  "casts": [
    "Dierdre Downing-Jackson",
    "Paul Carafotes",
    "Stuart Blumberg",
    "Holt McCallany",
    "Lauren Sánchez"
  ],
  "tags": [
    "Watch Fight Club Online Free,",
    "Fight Club Online Free,",
    "Where to watch Fight Club,",
    "Fight Club movie free online,",
    "Fight Club free online"
  ],
  "production": "Regency Enterprises",
  "country": "Germany",
  "duration": "139 min",
  "rating": 8.8,
  "episodes": [
    {
      "id": "19651",
      "title": "Fight Club Movie",
      "url": "https://flixhq.to/ajax/movie/episodes/19651"
    }
  ]
}

```

**Comment by BigNocciolino** [comment] 2022-10-03 15:37
> ah ok i see, i haven't had time to document this. `rm ~/.config/lobster/lobster_config.txt` should fix it

This worked for me

**Comment by olivluca** [comment] 2022-10-03 15:41
deleting the configuration file fixed it for me too.

**Comment by justchokingaround** [comment] 2022-10-03 21:16
mentioned in docs, closing this now

**Closed by justchokingaround** 2022-10-03 21:16 UTC

**Comment by EnigmaticJihad** [comment] 2022-10-07 07:28
`rm ~/.config/lobster/lobster_config.txt` didn't fix it for me. Then I tried uninstalling and installing again. Still facing the same problem.

**Comment by EnigmaticJihad** [comment] 2022-10-07 07:33
> `rm ~/.config/lobster/lobster_config.txt` didn't fix it for me. Then I tried uninstalling and installing again. Still facing the same problem.

Sorry, my bad. It's working now. **Thanks for fixing the script. I missed it a lot.**

**Comment by justchokingaround** [comment] 2022-10-07 12:02
I should've written that fix in the script itself but I didn't think about it 😔

**Comment by EnigmaticJihad** [comment] 2022-10-07 16:28
I'm glad `lobster` exits. Such a pleasure watching every movie and tv show from the terminal, where my progress is also saved. I'd love to contribute but unfortunately, my shell skills are dumb.
